const tests = [

/* ================= TESTI 1 (1–32) ================= */
[
{ question: "1. Ndihma e parë është ofrimi i kujdesit fillestar ndaj personit të lënduar në vendin e aksidentit.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "2. Qëllimi i ndihmës së parë është mbrojtja e jetës dhe parandalimi i ndërlikimeve.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "3. Gjatë dhënies së ndihmës së parë mund të përdoren:", options: ["Vetëm mjete standarde", "Vetëm mjete improvizuese", "Të dyja"], correct: 2 },
{ question: "4. Vendi i aksidentit duhet të sigurohet:", options: ["Me trekëndësh", "Me sinjalizim drite", "Me të dyja"], correct: 2 },
{ question: "5. Në rast aksidenti duhet:", options: ["Të çkyçet motori", "Të frenohet automjeti", "Të dyja"], correct: 2 },
{ question: "6. Për siguri personale përdoren:", options: ["Doreza", "Maskë", "Të dyja"], correct: 2 },
{ question: "7. Kontrollimi i vetëdijes bëhet duke:", options: ["Tundur shpatullat dhe pyet", "Pickuar", "Asnjëra"], correct: 0 },
{ question: "8. Gjatë thirrjes së ndihmës së shpejtë duhet dhënë të gjitha informacionet.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "9. Të lënduarit në rrezik:", options: ["Qëndrojnë të qetë", "Bërtasin", "Asnjëra"], correct: 0 },
{ question: "10. Pa vetëdije ekziston rreziku nga:", options: ["Kthimi i gjuhes prapa,mbyllja e rrugëve të frymëmarrjes dhe ngulfatja", "Ndalimi i zemrës", "Asnjëra"], correct: 0 },
{ question: "11. Kontrollimi i frymëmarrjes bëhet me:", options: ["Shiko, dëgjo, ndjej", "Pasqyrë", "Asnjëra"], correct: 0 },
{ question: "12. Gjakderdhja mund të jetë:", options: ["E jashtme", "E brendshme", "Të dyja"], correct: 2 },
{ question: "13. Tek i lënduari pa vetëdije së pari:", options: ["Kerkoni ndihmë te shpejt", "Jep ndihmën e pare", "Asnjëra"], correct: 1 },
{ question: "14. Raporti i RKP është:", options: ["30:2", "15:2", "15:5"], correct: 0 },
{ question: "15. Duart në masazh vendosen:", options: ["Nje te treten e siperme te gjoksit", "Ne mes gjoksit", "Nje te treten e poshte te gjoksit"], correct: 2 },
{ question: "16. RKP tek fëmijët 1–8 vjet:", options: ["15:2", "30:2", "15:1"], correct: 1 },
{ question: "17. Tek foshnjat fillohet me:", options: ["5 frymëmarrje", "2 frymëmarrje", "1 frymëmarrje"], correct: 0 },
{ question: "18. Kompresioni tek foshnjat bëhet me:", options: ["Dy duar", "Një dorë", "Dy gishta"], correct: 2 },
{ question: "19. Gjakderdhja arteriale ka gjak të zbehtë.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "20. Gjakderdhja e madhe shkakton shok.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "21. Për frymëmarrje artificiale përdoret maskë.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "22. Rreziku tek pa vetëdije është ngulfatja.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "23. Para ndihmës duhet pëlqimi i të dëmtuarit.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "24. Numri i ndihmës së shpejtë është 194.", options: ["E saktë", "Jo e saktë"], correct: 0 },
{ question: "25. Frakturë e këmbës imobilizon:", options: ["Gjuri & kyçi", "Bërryli", "Shpatulla"], correct: 0 },
{ question: "26. Rrobat priten nëse nuk hiqen.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "27. Triazhi përdoret kur ka shumë të lënduar.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "28. Person pa ndjenja me helmetë:", options: ["Hiq helmetën dhe jep RKP", "Mos e hiq"], correct: 0 },
{ question: "29. Personi i vetëdijshëm reagon.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "30. Frymëmarrja vlerësohet ≤10 sek.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "31. Mungesa e frymëmarrjes = arrest kardiak.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "32. Gjakderdhja është gjithmonë e dukshme.", options: ["E saktë", "Nuk është e saktë"], correct: 1 }
],

/* ================= TESTI 2 (33–63) ================= */
[
{ question: "33. Ekzaminimi bëhet nga:", options: ["Koka drejt këmbëve", "Këmbët drejt kokës", "Nuk bëhet"], correct: 0 },
{ question: "34. Tek i lenduari pa vetëdije dhe pa frymë:", options: ["Masazh zemre pastaj frymëmarje artificiale", "Frymë pastaj masazh", "Vetëm frymë"], correct: 0 },
{ question: "35. Nëse personi i lenduar merr frymë dhe eshte pa ndjenja vendoset anash.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "36. RKP jepet derisa:", options: ["Vjen ndihma e shpejt", "Personi fillon te mare frymë", "Të dyja"], correct: 2 },
{ question: "37. Masazhi tek fëmijët kryhet:", options: ["Një pëllëmbë", "Dy pëllëmbë", "Dy gishta"], correct: 0 },
{ question: "38. Ngulfatja patjeter duhet te:", options: ["Te goditet personi 5 here ne shpine", "5 shtypje barku", "Të fillohet me nje goditje ne shpine dhe pastaj 5 shtypje ne bark"], correct: 2 },
{ question: "39. Ne rast te ngulfatjes te foshnjat fillon me 5 goditen në shpinë.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "40. Gjakderdhja venoze është e errët.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "41. Gjakderdhja kapilare ka ngjyre te kuqe te çelët.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "42. Gjakderdhja arteriale ndalohet me:", options: ["Shtypje", "Fashë kompresimi", "Të dyja"], correct: 2 },
{ question: "43. Fasha kompresive përdoret  kur plaga rrjedh gjak, edhe pse është e mbuluar me një fashë normale:.", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "44. Nëse hasni një person të lënduar që ka një trup të huaj në plagë, është e nevojshme të bëni të njëjtën gjë:", options: ["Hiqet", "Nuk hiqet por lidheni me fashe gjevrek", "Asnjëra"], correct: 1 },
{ question: "45. Nëse hasni një person të lënduar me një dëmtim të dyshuar të shtyllës kurrizore, duhet të:", options: ["Mos lëvizni personin", "Transporto personin ne spital", "Ktheje anash"], correct: 0 },
{ question: "46. Procedura themelore në rast të një lëndimi që ka një frakturë është imobilizimi (vendosja e pjesës së thyer në një pozicion pushimi).", options: ["E saktë", "Nuk është e saktë"], correct: 0 },
{ question: "47. Imobilizimi (vendosja e pjesës së thyer në pozicion pushimi) në rast të frakturave mund të kryhet me: ", options: ["Mjete standarde", "Paketa për dhënien e ndihmës sëpare", "Të dyja"], correct: 2 },
{ question: "48. Gjatë lidhjes së plagës nuk duhet:", options: ["Ta prekni dhe pastroni", "Ta ngrini gjymtyrën", "Ta ngrohet i dëmtuari"], correct: 0 },
{ question: "49. Cila është procedura e parë që duhet të bëni në rast djegieje? ", options: ["Të ftohet vendi i djegur", "Vendosur krem", "Vendosur vaj"], correct: 0 },
{ question: "50. Nëse hasni një person që ka shtypur këmbët dhe nëse objekti që çoi në dërrmimin e tyre është në këmbë për më shumë se 15 minuta, atëherë objekti: ", options: ["Hiqet", "Nuk hiqet", "Hiqet pas 1 ore"], correct: 1 },
{ question: "51. Çfarë nuk duhet të përmbahet në çantën e ndihmës së parë që çdo shofer duhet të ketë në automjetin e tij?", options: ["Shami", "Fasho", "Alkool 70%"], correct: 2 },
{ question: "52. Çfarë ju mbron nga infeksioni kur jepni frymëmarrje artificiale (reanimacion kardiopulmonar - RKP)? ", options: ["Garzë sterile", "Shami ventilimi", "Foli metalike"], correct: 1 },
{ question: "53. Çfarë paraqet vendi i një aksidenti trafiku?", options: ["Rrezik për të lënduarit", "Rrezik për të gjithë pjesëmarrësit në trafik", "Jo rrezik"], correct: 1 },
{ question: "54. Koha për të cilën duhet të përcaktohet se ka ndërprerje të frymëmarrjes është: ", options: ["3–5 min", "30 sek", "10 sek"], correct: 2 },
{ question: "55. Çfarë nuk është e vërtetë për vendosjen e personit të dëmtuar në një pozicion anësor (pozicion shërimi)? ", options: ["Përmirëson qarkullimin në organet vitale", "Mban kalueshmërine e rrugëve të frymëmarjess", "Lejon kullim"], correct: 0 },
{ question: "56. Si duhet të trajtohet me të drejtë një plagë e cila rrjedh gjak? ", options: ["Mos e prek", "Doreza dhe garzë sterile në plagë", "Hiq trupat"], correct: 1 },
{ question: "57. Helmeta mbrojtëse e një personi të lënduar në një aksident trafiku nuk duhet të hiqet përveç kur ", options: ["Ka një thyerje të hapur dhe parakrah", "Nuk merr frymë", "Ka prerje"], correct: 1 },
{ question: "58. Cila nuk është shenjë e gjakderdhjes së rëndë (shoku hemorragjik)? ", options: ["Lëkurë e skuqur", "Lëkurë e zbehtë", "Puls i shpejtë"], correct: 0 },
{ question: "59. Nëse personi i dëmtuar ka një kofshë të thyer dhe gjakderdhje të rëndë në të njëjtën kohë, është e nevojshme që: ", options: ["Imobilizoni dhe pastaj ndaloni dhakderdhjen", "Ndal gjakun dhe pastaj imobilizoni", "Asnjëra"], correct: 1 },
{ question: "60. Nëse jeni duke imobilizuar një frakturë të parakrahit nuk duhet", options: ["Ta kapni dorë dhe bërrylin", "Të përdorni një Shall", "Të vendosni Shinën e kramerit vetëm te thyerja"], correct: 2 },
{ question: "61. Kur dyshoni për një dëmtim të palcës kurrizore në një person i cili është dëmtuar në një aksident automobilistik?", options: ["Nëse ka dhimbje koke", "Gjakderdhje", "Mpirje"], correct: 2 },
{ question: "62. Cila procedurë nuk zbatohet gjatë tërheqjes së një personi të lënduar nga një automjet ", options: ["Fik automjetik", "Zhblloko rripin", "Përkul përpara"], correct: 2 },
{ question: "63. Nëse një person është pa ndjenja, por merr frymë spontanisht dhe ka një puls, ai vendoset në: ", options: ["Në bark", "Në shpinë", "Anash"], correct: 2 }
],



];
